#!/bin/bash

docker run -d --rm --name sidekiq-web -w /app -v /home/ubuntu/data:/app/data  -e REDIS_URL=redis://redis:6379/0 -p 9292:9292 --network clinickr clinickr9 bash -c "rackup --port 9292 --host 0.0.0.0 config.ru" 
	